### ISSUE TITLE
Missing files for PredProcess code

### ISSUE THREAD

**Issue by bzki** [finnlindgren/heatoncomparison#1]
I noticed that the Predictive Process code in pp.R and pp-sim.R refer to some data that does not appear in the folder (files ending with `.mod`):

https://github.com/finnlindgren/heatoncomparison/blob/cd04a810b9eb74a8ca0a4c7e32b93dee2871c5ca/Code/PredProcess/pp.R#L6-L8

https://github.com/finnlindgren/heatoncomparison/blob/cd04a810b9eb74a8ca0a4c7e32b93dee2871c5ca/Code/PredProcess/pp-sim.R#L6-L8

I also think the README file here is not the correct one (it refers to NNGP results): https://github.com/finnlindgren/heatoncomparison/blob/master/Code/PredProcess/README

I sincerely appreciate you taking the time to make things reproducible and available on github.

**Comment by finnlindgren** [comment]
Confirmed that the README for PredProcess is wrong, and the reference to missing data files.
Will chase the authors of that part.

PS. Slow response due to start of semester.

**Comment by finnlindgren** [comment]
I believe d0493d43 fixes this issue.
